import { closestCenter, DndContext, KeyboardSensor, PointerSensor, useSensor, useSensors,
} from"@dnd-kit/core";
import { arrayMove, SortableContext, sortableKeyboardCoordinates,
} from"@dnd-kit/sortable";
import { Plus, Sword } from"lucide-react"; 

import Button from"@/components/atoms/Button";

import { SortableStepItem } from"./SortableStepItem"; const createNewStepTemplate = () => ({ type:"main", player:"", warning:"", variations: [], id: crypto.randomUUID(),
}); const StrategyEditor = ({ selectedEnemyPokemon, steps, onUpdateSteps }) => { const sensors = useSensors( useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates, }) ); const handleDragEnd = (event) => { const { active, over } = event; if (active.id !== over.id) { const oldIndex = steps.findIndex((step) => step.id === active.id); const newIndex = steps.findIndex((step) => step.id === over.id); onUpdateSteps(arrayMove(steps, oldIndex, newIndex)); } }; const addStep = () => { onUpdateSteps([...(steps || []), createNewStepTemplate()]); }; if (!selectedEnemyPokemon) { return ( <div className="animate-fade-in flex h-full flex-col items-center justify-center p-8 text-slate-500"> <div className="rounded-full bg-white/5 p-4"> <Sword size={32} className="opacity-50" /> </div> <p className="mt-4 text-sm font-medium"> Select an Enemy Pokémon from the sidebar to start planning. </p> </div> ); } return ( <div className="animate-fade-in flex h-full flex-col"> <div className="mb-6 flex items-center justify-between"> <div> <h2 className="text-2xl font-bold"> Vs. <span className="text-blue-400">{selectedEnemyPokemon}</span> </h2> <p className="text-xs text-slate-500"> Define your turn-by-turn strategy. </p> </div> <Button onClick={addStep} variant="primary" size="sm" icon={Plus}> Add Step </Button> </div> <div className="flex-1 space-y-4"> {steps && steps.length > 0 ? ( <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd} > <SortableContext items={steps.map((s) => s.id)}> <div className="space-y-4 pb-20"> {steps.map((step, i) => ( <SortableStepItem key={step.id} id={step.id} index={i} step={step} onChange={(updatedStep) => { const newSteps = [...steps]; newSteps[i] = updatedStep; onUpdateSteps(newSteps); }} onRemove={() => onUpdateSteps(steps.filter((_, idx) => idx !== i)) } /> ))} {/* Bottom Add Button */} <Button onClick={addStep} variant="ghost" size="lg" fullWidth className="border-dashed border-white/10 py-4 text-slate-500 hover:border-blue-500/30 hover:bg-blue-500/5 hover:text-blue-400" icon={Plus} > Add Next Step </Button> </div> </SortableContext> </DndContext> ) : ( <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-white/10 bg-[#1a1b20]/50 py-16 text-center"> <p className="mb-4 max-w-sm text-sm"> No plan defined for{""} <span className="text-blue-400">{selectedEnemyPokemon}</span> yet. </p> <Button onClick={addStep} variant="secondary" size="lg" icon={Plus}> Create First Step </Button> </div> )} </div> </div> );
};
export default StrategyEditor; 
