name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Type: Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: '🎨 UX/UI'
    labels:
      - 'Type: UX/UI'
  - title: '🛠️ Maintenance'
    labels:
      - 'Type: Chore'
      - 'Type: Refactor'
  - title: '📝 Documentation'
    labels:
      - 'Type: Docs'
  - title: '🧪 Testing'
    labels:
      - 'Type: Test'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/SolaneHub/PokeMMO-Compendium/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'Priority: Critical'
  minor:
    labels:
      - 'Type: Feature'
  patch:
    labels:
      - 'Type: Bug'
      - 'Type: Chore'
      - 'Type: Refactor'
      - 'Type: Test'
      - 'Type: UX/UI'
    default: true
