sonar.projectKey=SolaneHub_PokeMMO-Compendium
sonar.organization=solanehub

# Path to sources
sonar.sources=src
sonar.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/test/**/*
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Test Coverage - Vitest lcov format
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report/sonar-report.xml

# Quality Gate
sonar.qualitygate.wait=true
